import {Conversation} from '../types/message';

const CURRENT_USER_ID = '1'; // Sadiq

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    participantId: '2',
    participantName: 'Yonna Ray',
    participantHandle: '@yonnaray',
    participantAvatar: require('../assets/yonna1.jpg'),
    isOnline: true,
    lastMessage: 'gg! that last round was insane 🔥',
    lastMessageTime: '2m ago',
    unreadCount: 2,
    messages: [
      {
        id: 'm1',
        senderId: CURRENT_USER_ID,
        text: 'yo wanna run some val tonight?',
        timestamp: '9:14 PM',
        status: 'read',
        readAt: '9:15 PM',
      },
      {
        id: 'm2',
        senderId: '2',
        text: 'yesss i just got off work, lemme hop on',
        timestamp: '9:15 PM',
        status: 'read',
      },
      {
        id: 'm3',
        senderId: CURRENT_USER_ID,
        text: "bet. i'll start a lobby, you on PC or console?",
        timestamp: '9:16 PM',
        status: 'read',
        readAt: '9:16 PM',
      },
      {
        id: 'm4',
        senderId: '2',
        text: 'PC always 😤 loading up now',
        timestamp: '9:17 PM',
        status: 'read',
      },
      {
        id: 'm5',
        senderId: CURRENT_USER_ID,
        text: 'nice we just won that 3v5 lmaooo',
        timestamp: '10:42 PM',
        status: 'read',
        readAt: '10:42 PM',
      },
      {
        id: 'm6',
        senderId: '2',
        text: 'gg! that last round was insane 🔥',
        timestamp: '10:43 PM',
        status: 'read',
      },
    ],
  },
  {
    id: 'conv-2',
    participantId: '3',
    participantName: 'Marcus Chen',
    participantHandle: '@marcusc',
    participantAvatar: require('../assets/sadiq2.jpg'),
    isOnline: false,
    lastMessage: 'I hit Diamond 2 last night 💎',
    lastMessageTime: '1h ago',
    unreadCount: 0,
    messages: [
      {
        id: 'm1',
        senderId: '3',
        text: 'bro guess what',
        timestamp: '8:30 PM',
        status: 'read',
      },
      {
        id: 'm2',
        senderId: CURRENT_USER_ID,
        text: 'what happened??',
        timestamp: '8:31 PM',
        status: 'read',
        readAt: '8:31 PM',
      },
      {
        id: 'm3',
        senderId: '3',
        text: 'I hit Diamond 2 last night 💎',
        timestamp: '8:32 PM',
        status: 'read',
      },
    ],
  },
  {
    id: 'conv-3',
    participantId: '4',
    participantName: 'Kai Williams',
    participantHandle: '@kaiwill',
    participantAvatar: require('../assets/sadiq3.jpg'),
    isOnline: true,
    lastMessage: 'down for overwatch ranked?',
    lastMessageTime: '3h ago',
    unreadCount: 1,
    messages: [
      {
        id: 'm1',
        senderId: '4',
        text: 'hey! saw you play OW too',
        timestamp: '6:10 PM',
        status: 'read',
      },
      {
        id: 'm2',
        senderId: CURRENT_USER_ID,
        text: 'yea OW is my go-to lately',
        timestamp: '6:12 PM',
        status: 'read',
        readAt: '6:12 PM',
      },
      {
        id: 'm3',
        senderId: '4',
        text: 'down for overwatch ranked?',
        timestamp: '6:15 PM',
        status: 'read',
      },
    ],
  },
  {
    id: 'conv-4',
    participantId: '5',
    participantName: 'Ava Thompson',
    participantHandle: '@avat',
    participantAvatar: require('../assets/yonna2.jpg'),
    isOnline: false,
    lastMessage: 'that fortnite clip was crazy lol',
    lastMessageTime: '1d ago',
    unreadCount: 0,
    messages: [
      {
        id: 'm1',
        senderId: CURRENT_USER_ID,
        text: 'did you see that clutch I got?',
        timestamp: 'Yesterday',
        status: 'read',
        readAt: 'Yesterday',
      },
      {
        id: 'm2',
        senderId: '5',
        text: 'that fortnite clip was crazy lol',
        timestamp: 'Yesterday',
        status: 'read',
      },
    ],
  },
];
